version: '3'

services:
  cryptop2p:
    image: gradle:6.9.2-jdk17-alpine
    volumes:
      - ./:/home/gradle/project
    working_dir: /home/gradle/project
    # command: gradlew bootRun
    command: tail -f /dev/null
    ports:
      - 8080:8080
